#!/bin/bash
# ==============================================================================
# run_chain.sh - 通用处理链 wrapper
# ==============================================================================
# 在 HTCondor worker 上执行：
#   LHE -> Shower -> Mix -> GEN-SIM -> RAW -> RECO -> MiniAOD -> [可选] Ntuple
#
# 设计目标：
# 1. worker 节点运行时不再依赖 AFS 业务目录。
# 2. shower 模式使用统一枚举，兼容旧的 phi/sps 写法。
# 3. 支持本轮测试以 MiniAOD 为验收终点，同时保留 Ntuple 接口。
# ==============================================================================

set -e

# ==============================================================================
# Cleanup on Exit (trap)
# ==============================================================================
# This ensures intermediate files are always cleaned up, even on failure.
# This is critical to avoid HTCondor trying to transfer huge files (>1GB).
cleanup_on_exit() {
    local exit_code=$?
    if [[ "${CLEANUP}" == "true" ]] && [[ -n "${WORKDIR}" ]]; then
        echo "[INFO] Cleaning up intermediate files on exit (code=${exit_code})..."
        rm -f "${WORKDIR}"/*.hepmc 2>/dev/null || true
        rm -f "${WORKDIR}"/*.lhe 2>/dev/null || true
        rm -f "${WORKDIR}"/output_GENSIM.root 2>/dev/null || true
        rm -f "${WORKDIR}"/output_RAW.root 2>/dev/null || true
        rm -f "${WORKDIR}"/output_RECO.root 2>/dev/null || true
        rm -f "${WORKDIR}"/output_MINIAOD.root 2>/dev/null || true
        rm -f "${WORKDIR}"/output_ntuple.root 2>/dev/null || true
        rm -f "${WORKDIR}"/ntuple_*.root 2>/dev/null || true
        rm -f "${WORKDIR}"/.bash_history 2>/dev/null || true
        rm -f "${WORKDIR}"/.viminfo 2>/dev/null || true
        rm -rf "${WORKDIR}"/CMSSW_15_0_15 2>/dev/null || true
        echo "[INFO] Cleanup done"
    fi
    exit ${exit_code}
}
trap cleanup_on_exit EXIT

# ==============================================================================
# Configuration
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMMON_DIR="${BASE_DIR}/common"
SHOWER_DIR="${SCRIPT_DIR}/pythia_shower"
CMSSW_CONFIGS_DIR="${COMMON_DIR}/cmssw_configs"
PACKAGES_DIR="${COMMON_DIR}/packages"

# Fallback when run from a transferred sandbox (run_chain.sh + sibling folders)
if [[ ! -d "${COMMON_DIR}" && -d "${SCRIPT_DIR}/common" ]]; then
    BASE_DIR="${SCRIPT_DIR}"
    COMMON_DIR="${BASE_DIR}/common"
    SHOWER_DIR="${BASE_DIR}/pythia_shower"
    CMSSW_CONFIGS_DIR="${COMMON_DIR}/cmssw_configs"
    PACKAGES_DIR="${COMMON_DIR}/packages"
fi

# CMSSW paths (prefer node CVMFS installs; override via env if needed)
CMSSW_12_BASE="${CMSSW_12_BASE:-/cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_4_14}"
CMSSW_15_BASE="${CMSSW_15_BASE:-/cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_15_0_15}"

# T2_CN_Beijing XRootD storage paths
EOS_HOST="cceos.ihep.ac.cn"
EOS_XRDFS_TARGET="root://${EOS_HOST}"
EOS_PATH_BASE="/eos/ihep/cms/store/user/xcheng/MC_Production_v2"
EOS_BASE="root://${EOS_HOST}/${EOS_PATH_BASE}"
EOS_LHE_POOL="${EOS_BASE}/lhe_pools"
EOS_OUTPUT="${EOS_BASE}/output"

# LHE pools on T2_CN_Beijing storage
# All pools will be generated by DAG LHE jobs
declare -A EXISTING_POOLS=(
    # Pools will be populated by DAG generator as they become available
)

# workbook_v2 中只有 pool_2jpsi 需要在 worker 上做按截面混合解析。
declare -A COMPOSITE_POOL_VARIANTS=(
    ["pool_2jpsi"]="pool_2jpsi_cs,pool_2jpsi_g"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Avoid leaving shell history files
export HISTFILE=/dev/null
export HISTSIZE=0
export HISTFILESIZE=0

if [[ ! -d "${COMMON_DIR}" ]]; then
    echo "[ERROR] Common directory not found at ${COMMON_DIR}. Ensure common/ is transferred alongside run_chain.sh."
    exit 1
fi

# ==============================================================================
# Utility Functions
# ==============================================================================

msg_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
msg_ok() { echo -e "${GREEN}[OK]${NC} $1"; }
msg_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
msg_error() { echo -e "${RED}[ERROR]${NC} $1"; }
msg_step() { echo -e "\n${YELLOW}========================================${NC}"; echo -e "${YELLOW}  $1${NC}"; echo -e "${YELLOW}========================================${NC}\n"; }

# 高噪声命令统一写入 worker 本地日志，避免 Condor stdout/stderr 过大被 hold。
JOB_LOG_DIR=""
COMMAND_LOG_INDEX=0

sanitize_log_label() {
    local raw_label="$1"
    printf '%s' "${raw_label}" | sed 's/[^A-Za-z0-9._-]/_/g'
}

ensure_job_log_dir() {
    if [[ -n "${JOB_LOG_DIR}" ]]; then
        mkdir -p "${JOB_LOG_DIR}"
        return 0
    fi
    if [[ -z "${WORKDIR:-}" ]]; then
        return 1
    fi
    JOB_LOG_DIR="${WORKDIR}/command_logs"
    mkdir -p "${JOB_LOG_DIR}"
}

show_log_tail() {
    local label="$1"
    local file_path="$2"
    local max_lines="$3"
    if [[ -s "${file_path}" ]]; then
        msg_warn "${label} 摘要 (${file_path}, tail -n ${max_lines})"
        tail -n "${max_lines}" "${file_path}"
    fi
}

run_logged() {
    local label="$1"
    shift

    ensure_job_log_dir || {
        msg_error "无法初始化本地命令日志目录"
        return 1
    }

    COMMAND_LOG_INDEX=$((COMMAND_LOG_INDEX + 1))
    local safe_label=""
    safe_label=$(sanitize_log_label "${label}")
    local log_prefix
    printf -v log_prefix "%s/%03d_%s" "${JOB_LOG_DIR}" "${COMMAND_LOG_INDEX}" "${safe_label}"
    local stdout_log="${log_prefix}.stdout"
    local stderr_log="${log_prefix}.stderr"
    local rc=0
    local stdout_size=0
    local stderr_size=0

    msg_info "执行 ${label}，详细日志写入 ${log_prefix}.[stdout|stderr]"
    if "$@" >"${stdout_log}" 2>"${stderr_log}"; then
        stdout_size=$(wc -c < "${stdout_log}" 2>/dev/null || echo 0)
        stderr_size=$(wc -c < "${stderr_log}" 2>/dev/null || echo 0)
        msg_ok "${label} 完成 (stdout=${stdout_size} B, stderr=${stderr_size} B)"
        return 0
    fi

    rc=$?
    msg_error "${label} 失败 (rc=${rc})"
    show_log_tail "${label} stderr" "${stderr_log}" 80 >&2
    show_log_tail "${label} stdout" "${stdout_log}" 40
    return "${rc}"
}

normalize_shower_mode() {
    case "$1" in
        normal)
            echo "normal"
            ;;
        phi|phi_default|phi_mode1|phi_mpi_off|sps)
            echo "phi_mpi_off"
            ;;
        phi_mode2|phi_mpi_on_gluon|phi_gluon)
            echo "phi_mpi_on_gluon"
            ;;
        *)
            return 1
            ;;
    esac
}

# XRootD tools from CVMFS (compatible with el8 containers)
XROOTD_BASE="/cvmfs/cms.cern.ch/el8_amd64_gcc10/external/xrootd/5.5.0-a0410a6758fd4d07b495e4c473820f38"
XROOTD_BIN="${XROOTD_BASE}/bin"
XROOTD_LIB="${XROOTD_BASE}/lib64"
GCC10_LIB="/cvmfs/cms.cern.ch/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/lib64"
# Clean LD_LIBRARY_PATH for xrootd tools (only el8 libs)
XROOTD_LD_PATH="${XROOTD_LIB}:${GCC10_LIB}:/lib64:/usr/lib64"

# Run xrdfs with clean el8 environment (avoid CMSSW el9 library conflicts)
run_xrdfs() {
    env LD_LIBRARY_PATH="${XROOTD_LD_PATH}" "${XROOTD_BIN}/xrdfs" "$@"
}

# Run xrdcp with clean el8 environment (avoid CMSSW el9 library conflicts)
run_xrdcp() {
    env LD_LIBRARY_PATH="${XROOTD_LD_PATH}" "${XROOTD_BIN}/xrdcp" "$@"
}

# Convert HELAC 9900xxxx octet codes to Pythia OniaShower 99nqnsnrnLnJ scheme
convert_lhe_octet_codes() {
    local lhe_file="$1"
    local octet_tool="${COMMON_DIR}/octet_pdg.py"
    if [[ ! -f "${lhe_file}" ]]; then
        msg_error "LHE file not found for conversion: ${lhe_file}"
        return 1
    fi
    if [[ ! -f "${octet_tool}" ]]; then
        msg_error "Octet PDG tool not found: ${octet_tool}"
        return 1
    fi
    if ! grep -q "\<9900" "${lhe_file}"; then
        return 0
    fi
    msg_info "Converting color-octet PDG codes in ${lhe_file}..."
    PYTHONIOENCODING=UTF-8 python3 "${octet_tool}" convert-file "${lhe_file}" --in-place >/dev/null
    PYTHONIOENCODING=UTF-8 python3 "${octet_tool}" scan "${lhe_file}" --fail-on-legacy
}

# Create remote directory via XRootD
make_remote_dir() {
    local remote_subpath="$1"
    msg_info "Creating remote directory: ${EOS_PATH_BASE}/${remote_subpath}"
    run_logged "xrdfs_mkdir_${remote_subpath//\//_}" run_xrdfs "${EOS_XRDFS_TARGET}" mkdir -p "${EOS_PATH_BASE}/${remote_subpath}" || {
        msg_error "Failed to create remote directory: ${EOS_PATH_BASE}/${remote_subpath}"
        return 1
    }
    msg_ok "Remote directory ready: ${EOS_PATH_BASE}/${remote_subpath}"
}

# Stage out files via XRootD
stage_out() {
    local local_file="$1"
    local remote_subpath="$2"
    
    if [[ ! -f "${local_file}" ]]; then
        msg_error "Local file not found: ${local_file}"
        return 1
    fi
    
    local remote_url="${EOS_BASE}/${remote_subpath}"
    msg_info "Staging out: ${local_file} -> ${remote_url}"
    
    run_logged "xrdcp_stageout_$(basename "${local_file}")" run_xrdcp --nopbar --force "${local_file}" "${remote_url}" || {
        msg_error "Failed to stage out ${local_file} to ${remote_url}"
        return 1
    }
    msg_ok "Staged out: ${remote_url}"
}

get_lhe_file() {
    local pool_name="$1"
    local index="$2"
    local pool_subpath=""
    local files=()
    local n_files=0
    local file_idx=0

    if ! mapfile -t files < <(list_lhe_files "${pool_name}"); then
        return 1
    fi

    n_files=${#files[@]}
    if [[ ${n_files} -eq 0 ]]; then
        if [[ -n "${EXISTING_POOLS[$pool_name]}" ]]; then
            pool_subpath="${EXISTING_POOLS[$pool_name]}"
        else
            pool_subpath="lhe_pools/${pool_name}"
        fi
        msg_error "No LHE files found in ${EOS_PATH_BASE}/${pool_subpath}" >&2
        return 1
    fi

    file_idx=$((index % n_files))
    echo "${files[$file_idx]}"
}

list_lhe_files() {
    local pool_name="$1"
    local pool_subpath=""
    local file_list=""

    if [[ -n "${EXISTING_POOLS[$pool_name]}" ]]; then
        pool_subpath="${EXISTING_POOLS[$pool_name]}"
    else
        pool_subpath="lhe_pools/${pool_name}"
    fi

    if ! file_list=$(run_xrdfs "${EOS_XRDFS_TARGET}" ls "${EOS_PATH_BASE}/${pool_subpath}" 2>/dev/null | grep '\.lhe$' | sort); then
        msg_error "Failed to list LHE files via xrdfs at ${EOS_PATH_BASE}/${pool_subpath}" >&2
        return 1
    fi

    if [[ -z "${file_list}" ]]; then
        return 0
    fi

    while IFS= read -r line; do
        [[ -n "${line}" ]] || continue
        printf 'root://%s/%s\n' "${EOS_HOST}" "${line}"
    done <<< "${file_list}"
}

extract_lhe_cross_section_pb() {
    local lhe_file="$1"
    awk '
        /<init>/ { in_init=1; next }
        in_init && seen_header == 0 {
            if (NF > 0) {
                seen_header = 1
            }
            next
        }
        in_init && seen_header == 1 && NF > 0 {
            print $1
            exit
        }
    ' "${lhe_file}"
}

estimate_pool_cross_section_pb() {
    local pool_name="$1"
    local sample_url="$2"
    local cache_file="${WORKDIR}/.xsec_${pool_name}.txt"
    local sample_file="${WORKDIR}/.${pool_name}_xsec_sample.lhe"
    local xsec=""
    local cleanup_sample=0

    mkdir -p "${WORKDIR}"

    if [[ -f "${cache_file}" ]]; then
        cat "${cache_file}"
        return 0
    fi

    if [[ "${sample_url}" == root://* ]]; then
        if ! run_xrdcp --nopbar --force "${sample_url}" "${sample_file}" >/dev/null 2>&1; then
            return 1
        fi
        cleanup_sample=1
    else
        sample_file="${sample_url}"
    fi

    if [[ -f "${sample_file}" ]]; then
        xsec=$(extract_lhe_cross_section_pb "${sample_file}" | head -n 1)
    fi

    if [[ ${cleanup_sample} -eq 1 ]]; then
        rm -f "${sample_file}"
    fi

    if [[ -z "${xsec}" ]]; then
        return 1
    fi

    printf '%s\n' "${xsec}" > "${cache_file}"
    printf '%s\n' "${xsec}"
}

select_composite_variant() {
    local pool_name="$1"
    local job_index="$2"
    local usage_index="$3"
    local variants_csv="${COMPOSITE_POOL_VARIANTS[$pool_name]:-}"
    local variants=()
    local active_variants=()
    local active_weights=()
    local variant=""
    local files=()
    local weight=""
    local selected_variant=""
    local selector_key=0
    local index=0

    if [[ -z "${variants_csv}" ]]; then
        msg_error "Composite pool is not configured: ${pool_name}" >&2
        return 1
    fi

    IFS=',' read -ra variants <<< "${variants_csv}"

    for variant in "${variants[@]}"; do
        if ! mapfile -t files < <(list_lhe_files "${variant}"); then
            return 1
        fi
        if [[ ${#files[@]} -eq 0 ]]; then
            msg_warn "Composite sub-pool has no files and will be skipped: ${variant}" >&2
            continue
        fi

        if ! weight=$(estimate_pool_cross_section_pb "${variant}" "${files[0]}"); then
            weight="1.0"
            msg_warn "Failed to extract cross section for ${variant}; fallback to equal weight" >&2
        fi

        active_variants+=("${variant}")
        active_weights+=("${weight}")
    done

    if [[ ${#active_variants[@]} -eq 0 ]]; then
        msg_error "No usable sub-pool found for composite pool ${pool_name}" >&2
        return 1
    fi

    if [[ ${#active_variants[@]} -eq 1 ]]; then
        printf '%s\n' "${active_variants[0]}"
        return 0
    fi

    selector_key=$(( (job_index + 1) * 104729 + (usage_index + 1) * 1009 ))
    selected_variant=$(awk \
        -v variants="$(IFS=,; echo "${active_variants[*]}")" \
        -v weights="$(IFS=,; echo "${active_weights[*]}")" \
        -v key="${selector_key}" \
        'BEGIN {
            n = split(variants, v, ",")
            split(weights, w, ",")
            total = 0.0
            for (i = 1; i <= n; ++i) {
                total += (w[i] + 0.0)
            }
            if (total <= 0.0) {
                print v[1]
                exit
            }
            frac = ((key * 1103515245 + 12345) % 1000000) / 1000000.0
            acc = 0.0
            for (i = 1; i <= n; ++i) {
                acc += (w[i] + 0.0) / total
                if (frac < acc) {
                    print v[i]
                    exit
                }
            }
            print v[n]
        }')

    if [[ -z "${selected_variant}" ]]; then
        selected_variant="${active_variants[0]}"
    fi

    for index in "${!active_variants[@]}"; do
        if [[ "${active_variants[$index]}" == "${selected_variant}" ]]; then
            msg_info "Composite pool ${pool_name}: selected ${selected_variant} (sigma=${active_weights[$index]} pb)" >&2
            break
        fi
    done

    printf '%s\n' "${selected_variant}"
}

resolve_composite_lhe_file() {
    local pool_name="$1"
    local job_index="$2"
    local usage_index="$3"
    local selected_variant=""
    local selected_file=""
    local variant_file_index=0

    selected_variant=$(select_composite_variant "${pool_name}" "${job_index}" "${usage_index}") || return 1
    variant_file_index=$((job_index + usage_index))
    selected_file=$(get_lhe_file "${selected_variant}" "${variant_file_index}") || return 1
    printf '%s\n' "${selected_file}"
}

# Check if a remote XRootD file exists
check_remote_file() {
    local url="$1"
    if [[ "$url" == root://* ]]; then
        # Extract host and path from XRootD URL
        local host_path="${url#root://}"
        local host="${host_path%%/*}"
        local path="/${host_path#*/}"
        run_xrdfs "root://${host}" stat "${path}" &>/dev/null
        return $?
    else
        # Local file check
        [[ -f "$url" ]]
        return $?
    fi
}

# Ensure CMSSW_12 project exists in workdir (created on demand from CVMFS release)
ensure_cmssw12_project() {
    local project_dir="${WORKDIR}/CMSSW_12_4_14"
    
    if [[ -d "${project_dir}/src" ]]; then
        echo "${project_dir}"
        return 0
    fi
    
    # Use stderr for info messages to avoid polluting function return value
    msg_info "Creating CMSSW_12_4_14 project from CVMFS..." >&2
    source /cvmfs/cms.cern.ch/cmsset_default.sh
    export SCRAM_ARCH=el8_amd64_gcc10
    
    cd "${WORKDIR}"
    run_logged "scram_project_CMSSW_12_4_14" scramv1 project CMSSW CMSSW_12_4_14 >&2 || {
        msg_error "Failed to create CMSSW_12_4_14 project" >&2
        return 1
    }
    cd - > /dev/null
    
    echo "${project_dir}"
}

setup_cmssw12() {
    msg_info "Setting up CMSSW_12_4_14..."
    source /cvmfs/cms.cern.ch/cmsset_default.sh
    # Force el8 architecture for CMSSW_12
    export SCRAM_ARCH=el8_amd64_gcc10
    
    # Create project on demand if needed
    local base_path
    base_path=$(ensure_cmssw12_project) || return 1
    export CMSSW_12_BASE="${base_path}"

    cd "${base_path}/src"
    eval $(scramv1 runtime -sh)
    cd - > /dev/null
    msg_ok "CMSSW environment: ${CMSSW_VERSION}"
}

# Ensure CMSSW_15 project exists in workdir (created on demand from CVMFS release)
ensure_cmssw15_project() {
    local project_dir="${WORKDIR}/CMSSW_15_0_15"
    
    if [[ -d "${project_dir}/src" ]]; then
        echo "${project_dir}"
        return 0
    fi
    
    # Use stderr for info messages to avoid polluting function return value
    msg_info "Creating CMSSW_15_0_15 project from CVMFS in el9 container..." >&2
    
    local tmp_script=$(mktemp --suffix=_create_cmssw15.sh)
    cat > "${tmp_script}" << CREATEEOF
#!/bin/bash
set -e
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=el9_amd64_gcc12
cd "${WORKDIR}"
scramv1 project CMSSW CMSSW_15_0_15
CREATEEOF
    chmod +x "${tmp_script}"
    
    run_logged "apptainer_create_CMSSW_15_0_15" apptainer exec \
        --bind /cvmfs:/cvmfs \
        --bind /tmp:/tmp \
        --bind "${WORKDIR}:${WORKDIR}" \
        "${EL9_CONTAINER}" \
        /bin/bash "${tmp_script}" >&2
    
    local rc=$?
    rm -f "${tmp_script}"
    
    if [[ $rc -ne 0 ]]; then
        msg_error "Failed to create CMSSW_15_0_15 project" >&2
        return 1
    fi
    
    echo "${project_dir}"
}

setup_cmssw15() {
    msg_info "Setting up CMSSW_15_0_15..."
    
    # Create project on demand if needed
    local base_path
    base_path=$(ensure_cmssw15_project) || return 1
    export CMSSW_15_BASE="${base_path}"

    # Note: CMSSW_15 is built in el9 container, setup happens in container too
    source /cvmfs/cms.cern.ch/cmsset_default.sh
    # Force el9 architecture for CMSSW_15
    export SCRAM_ARCH=el9_amd64_gcc12
    cd "${base_path}/src"
    eval $(scramv1 runtime -sh)
    cd - > /dev/null
    msg_ok "CMSSW environment: ${CMSSW_VERSION}"
}

# EL9 container path for CMSSW_15
EL9_CONTAINER="/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el9:x86_64"

# Run command inside el9 container using apptainer
run_in_el9_container() {
    local script_content="$1"
    local tmp_script=$(mktemp --suffix=_el9_cmd.sh)
    
    cat > "${tmp_script}" << 'SCRIPT_HEADER'
#!/bin/bash
set -e
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=el9_amd64_gcc12
SCRIPT_HEADER
    
    echo "${script_content}" >> "${tmp_script}"
    chmod +x "${tmp_script}"
    
    # Run in el9 container with necessary bind mounts
    apptainer exec \
        --bind /cvmfs:/cvmfs \
        --bind /tmp:/tmp \
        --bind "${WORKDIR}:${WORKDIR}" \
        "${EL9_CONTAINER}" \
        /bin/bash "${tmp_script}"
    
    local rc=$?
    rm -f "${tmp_script}"
    return ${rc}
}

run_cmsrun_cmssw15() {
    local cfg="$1"
    shift
    
    msg_info "Running cmsRun in el9 container for CMSSW_15..."
    
    # Build the full command with arguments
    local tmp_script=$(mktemp --suffix=_cmsrun.sh)
    cat > "${tmp_script}" << SCRIPT_EOF
#!/bin/bash
set -e
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=el9_amd64_gcc12
cd "${CMSSW_15_BASE}/src"
eval \$(scramv1 runtime -sh)
cmsRun "${cfg}" $@
SCRIPT_EOF
    
    chmod +x "${tmp_script}"
    
    run_logged "apptainer_cmsRun_$(basename "${cfg}")" apptainer exec \
        --bind /cvmfs:/cvmfs \
        --bind /tmp:/tmp \
        --bind "${WORKDIR}:${WORKDIR}" \
        --env "X509_USER_PROXY=${X509_USER_PROXY:-}" \
        --env "HOME=${HOME}" \
        "${EL9_CONTAINER}" \
        /bin/bash "${tmp_script}"
    
    local rc=$?
    rm -f "${tmp_script}"
    return ${rc}
}

ensure_voms_proxy() {
    msg_info "Checking VOMS proxy for pileup access..."

    # Prefer user-provided proxy if already set
    if [[ -z "${X509_USER_PROXY:-}" ]] && [[ -f "/tmp/x509up_u$(id -u)" ]]; then
        export X509_USER_PROXY="/tmp/x509up_u$(id -u)"
        msg_info "Using default proxy path: ${X509_USER_PROXY}"
    fi

    if command -v voms-proxy-info >/dev/null 2>&1; then
        if voms-proxy-info --exists >/dev/null 2>&1; then
            local tl
            tl=$(voms-proxy-info --timeleft 2>/dev/null || true)
            msg_ok "VOMS proxy valid (timeleft: ${tl}s)"
            return 0
        fi
    else
        msg_warn "voms-proxy-info not found; skipping proxy validation"
        return 0
    fi

    msg_warn "No valid VOMS proxy detected. If DIGI premix download fails, run: voms-proxy-init -voms cms -valid 192:00"
}

prepare_cmssw15_from_package() {
    local analysis="$1"
    local pkg=""

    case "${analysis}" in
        "JJP") pkg="${PACKAGES_DIR}/jjp_code.tar.gz" ;;
        "JUP") pkg="${PACKAGES_DIR}/jup_code.tar.gz" ;;
        *) msg_error "Unknown analysis type for CMSSW_15 build: ${analysis}"; return 1 ;;
    esac

    if [[ ! -d "${PACKAGES_DIR}" ]]; then
        msg_error "Packages directory missing: ${PACKAGES_DIR}"
        return 1
    fi
    if [[ ! -f "${pkg}" ]]; then
        msg_error "Package not found: ${pkg} (ensure common/packages is transferred)"
        return 1
    fi

    local project_dir="${WORKDIR}/CMSSW_15_0_15"
    export CMSSW_15_BASE="${project_dir}"
    
    if [[ ! -d "${project_dir}/src" ]]; then
        msg_info "Creating CMSSW_15_0_15 project in el9 container at ${project_dir}..."
        
        local tmp_script=$(mktemp --suffix=_create_cmssw15.sh)
        cat > "${tmp_script}" << CREATEEOF
#!/bin/bash
set -e
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=el9_amd64_gcc12
cd "${WORKDIR}"
scramv1 project CMSSW CMSSW_15_0_15
CREATEEOF
        chmod +x "${tmp_script}"
        
        run_logged "apptainer_create_CMSSW_15_0_15_pkg" apptainer exec \
            --bind /cvmfs:/cvmfs \
            --bind /tmp:/tmp \
            --bind "${WORKDIR}:${WORKDIR}" \
            "${EL9_CONTAINER}" \
            /bin/bash "${tmp_script}"
        rm -f "${tmp_script}"
    fi

    # The worker package is expected under <channel>/TPS_Onia2MuMu/.
    local pkg_check_dir=""
    case "${analysis}" in
        "JJP") pkg_check_dir="${project_dir}/src/JJPNtupleMaker/TPS_Onia2MuMu" ;;
        "JUP") pkg_check_dir="${project_dir}/src/JUPNtupleMaker/TPS_Onia2MuMu" ;;
    esac
    
    if [[ ! -d "${pkg_check_dir}" ]]; then
        msg_info "Unpacking ${pkg} into CMSSW src..."
        tar -xzf "${pkg}" -C "${project_dir}/src"
    fi

    local stamp="${project_dir}/.built_${analysis,,}"
    if [[ ! -f "${stamp}" ]]; then
        msg_info "Compiling ntuple code for ${analysis} in el9 container..."
        
        local tmp_script=$(mktemp --suffix=_build_cmssw15.sh)
        cat > "${tmp_script}" << BUILDEOF
#!/bin/bash
set -e
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=el9_amd64_gcc12
cd "${project_dir}/src"
eval \$(scramv1 runtime -sh)
scram b -j 4
BUILDEOF
        chmod +x "${tmp_script}"
        
        run_logged "apptainer_scram_b_${ANALYSIS_TYPE}" apptainer exec \
            --bind /cvmfs:/cvmfs \
            --bind /tmp:/tmp \
            --bind "${WORKDIR}:${WORKDIR}" \
            "${EL9_CONTAINER}" \
            /bin/bash "${tmp_script}"
        rm -f "${tmp_script}"
        
        touch "${stamp}"
    else
        msg_info "Reusing existing CMSSW_15_0_15 build for ${analysis}"
    fi
}

ntuple_package_dir() {
    case "$1" in
        "JJP") echo "${CMSSW_15_BASE}/src/JJPNtupleMaker/TPS_Onia2MuMu" ;;
        "JUP") echo "${CMSSW_15_BASE}/src/JUPNtupleMaker/TPS_Onia2MuMu" ;;
        *) return 1 ;;
    esac
}

ntuple_analysis_mode() {
    case "$1" in
        "JJP") echo "JpsiJpsiPhi" ;;
        "JUP") echo "JpsiUpsPhi" ;;
        *) return 1 ;;
    esac
}

ntuple_cfg_path() {
    local package_dir="$1"
    echo "${package_dir}/test/ConfFile_cfg.py"
}

# ==============================================================================
# Processing Steps
# ==============================================================================

SHOWER_BUILD_DONE="false"

ensure_worker_shower_tools() {
    if [[ "${SHOWER_BUILD_DONE}" == "true" ]]; then
        return 0
    fi

    msg_info "Rebuilding shower/mixer tools inside worker for ABI compatibility..."
    run_logged "build_pythia_shower_tools" make -B all
    SHOWER_BUILD_DONE="true"
}

# Step 1: Shower LHE files
run_shower() {
    local lhe_files=("$@")
    local n_files=${#lhe_files[@]}
    local n_modes=${#SHOWER_MODES[@]}
    
    msg_step "Step 1: Pythia8 Shower"
    
    if [[ $n_files -ne $n_modes ]]; then
        msg_error "Number of LHE files ($n_files) doesn't match modes ($n_modes)"
        return 1
    fi
    
    local shower_events=-1
    if [[ "${MAX_EVENTS}" -gt 0 ]]; then
        shower_events="${MAX_EVENTS}"
    fi

    HEPMC_FILES=()
    
    setup_cmssw12
    cd "${SHOWER_DIR}"
    ensure_worker_shower_tools || return 1
    
    for ((i=0; i<n_files; i++)); do
        local lhe_file="${lhe_files[$i]}"
        local mode="${SHOWER_MODES[$i]}"
        local normalized_mode=""
        local hepmc_output="${WORKDIR}/shower_${i}.hepmc"
        local local_lhe="${WORKDIR}/input_${i}.lhe"
        
        msg_info "Processing source $((i+1))/${n_files}: ${lhe_file}"
        if ! normalized_mode=$(normalize_shower_mode "${mode}"); then
            msg_error "Unknown shower mode: ${mode}"
            return 1
        fi
        msg_info "Shower mode: ${mode} -> ${normalized_mode}"
        
        # Download LHE file if it's a remote XRootD URL
        if [[ "$lhe_file" == root://* ]]; then
            msg_info "Downloading LHE from XRootD..."
            run_logged "xrdcp_input_lhe_${i}" run_xrdcp -f "${lhe_file}" "${local_lhe}"
            if [[ $? -ne 0 ]] || [[ ! -f "${local_lhe}" ]]; then
                msg_error "Failed to download LHE file from ${lhe_file}"
                return 1
            fi
            msg_ok "Downloaded: ${local_lhe}"
            lhe_file="${local_lhe}"
        fi

        # Convert HELAC 9900xxxx octet codes to OniaShower 99nqnsnrnLnJ scheme
        # Note: With parton_shower=1 in HELAC-Onia, the *_py8.lhe files should
        # already have correct Pythia8 PDG codes. This conversion handles any
        # remaining HELAC-style codes that might be present.
        convert_lhe_octet_codes "${lhe_file}"
        
        if [[ "$normalized_mode" == "phi_mpi_off" ]]; then
            # workbook_v2 默认模式：关闭 MPI，循环 hadronize 找 phi。
            msg_info "Running phi-enriched mode-1 shower (MPI off)..."
            run_logged "shower_sps_${i}" ./shower_sps "${lhe_file}" "${hepmc_output}" "${shower_events}" 3.0 2.5 2.4 5000
        elif [[ "$normalized_mode" == "phi_mpi_on_gluon" ]]; then
            # 扩展模式：开启 MPI，并交给 shower_phi 处理来源判定。
            msg_info "Running phi-enriched mode-2 shower (MPI on)..."
            run_logged "shower_phi_${i}" ./shower_phi "${lhe_file}" "${hepmc_output}" "${shower_events}" 3.0 2.5 2.4 5000 1
        else
            # 普通 shower。
            run_logged "shower_normal_${i}" ./shower_normal "${lhe_file}" "${hepmc_output}" "${shower_events}" 2.5 2.4 1000
        fi
        
        if [[ ! -f "${hepmc_output}" ]]; then
            msg_error "Shower failed: ${hepmc_output} not created"
            return 1
        fi
        
        HEPMC_FILES+=("${hepmc_output}")
        msg_ok "Shower complete: ${hepmc_output}"
    done
    
    cd "${WORKDIR}"
}

# Step 2: Mix HepMC files
run_mix() {
    msg_step "Step 2: Event Mixing"
    
    local n_sources=${#HEPMC_FILES[@]}
    MIXED_HEPMC="${WORKDIR}/mixed.hepmc"
    
    cd "${SHOWER_DIR}"
    ensure_worker_shower_tools || return 1
    
    if [[ $n_sources -eq 1 ]]; then
        msg_info "Single source - converting to HepMC2 format..."
        run_logged "event_mixer_single" ./event_mixer_multisource "${MIXED_HEPMC}" "${HEPMC_FILES[0]}"
    else
        msg_info "Mixing ${n_sources} sources..."
        run_logged "event_mixer_multi" ./event_mixer_multisource "${MIXED_HEPMC}" "${HEPMC_FILES[@]}"
    fi
    
    if [[ ! -f "${MIXED_HEPMC}" ]]; then
        msg_error "Mixing failed: ${MIXED_HEPMC} not created"
        return 1
    fi
    
    msg_ok "Mixing complete: ${MIXED_HEPMC}"
    cd "${WORKDIR}"
}

# Step 3: GEN-SIM
run_gensim() {
    msg_step "Step 3: GEN-SIM"
    
    GENSIM_OUTPUT="${WORKDIR}/output_GENSIM.root"

    # When resuming with --skip-to gensim, ensure MIXED_HEPMC points to the
    # expected mixed file in the workdir.
    MIXED_HEPMC="${MIXED_HEPMC:-${WORKDIR}/mixed.hepmc}"
    if [[ ! -f "${MIXED_HEPMC}" ]]; then
        msg_error "GEN-SIM input missing: ${MIXED_HEPMC}"
        return 1
    fi
    
    setup_cmssw12
    
    msg_info "Running HepMC -> GEN-SIM..."
    run_logged "cmsRun_hepmc_to_GENSIM" cmsRun "${CMSSW_CONFIGS_DIR}/hepmc_to_GENSIM.py" \
        inputFiles="file:${MIXED_HEPMC}" \
        outputFile="file:${GENSIM_OUTPUT}" \
        maxEvents=${MAX_EVENTS} \
        nThreads=4
    
    if [[ ! -f "${GENSIM_OUTPUT}" ]]; then
        msg_error "GEN-SIM failed: ${GENSIM_OUTPUT} not created"
        return 1
    fi
    
    msg_ok "GEN-SIM complete: ${GENSIM_OUTPUT}"
}

# Step 4: RAW (DIGI + HLT)
run_raw() {
    msg_step "Step 4: RAW (DIGI + HLT)"
    
    RAW_OUTPUT="${WORKDIR}/output_RAW.root"
    
    setup_cmssw12
    
    local cfg_file=$(mktemp --suffix=_raw_cfg.py)
    
    msg_info "Generating RAW config..."
    run_logged "cmsDriver_step2_raw" cmsDriver.py step2 \
        --mc --no_exec \
        --python_filename "${cfg_file}" \
        --eventcontent PREMIXRAW \
        --step DIGI,DATAMIX,L1,DIGI2RAW,HLT:2022v12 \
        --procModifiers premix_stage2,siPixelQualityRawToDigi \
        --datamix PreMix \
        --datatier GEN-SIM-RAW \
        --conditions 124X_mcRun3_2022_realistic_v12 \
        --beamspot Realistic25ns13p6TeVEarly2022Collision \
        --era Run3 \
        --geometry DB:Extended \
        -n "${MAX_EVENTS}" \
        --customise Configuration/DataProcessing/Utils.addMonitoring \
        --nThreads 4 --nStreams 4 \
        --pileup_input "filelist:/cvmfs/cms.cern.ch/offcomp-prod/premixPUlist/PREMIX-Run3Summer22DRPremix.txt" \
        --filein "file:${GENSIM_OUTPUT}" \
        --fileout "file:${RAW_OUTPUT}"
    
    msg_info "Running RAW step..."
    run_logged "cmsRun_step2_raw" cmsRun "${cfg_file}"
    rm -f "${cfg_file}"
    
    if [[ ! -f "${RAW_OUTPUT}" ]]; then
        msg_error "RAW step failed: ${RAW_OUTPUT} not created"
        return 1
    fi
    
    msg_ok "RAW complete: ${RAW_OUTPUT}"
}

# Step 5: RECO
run_reco() {
    msg_step "Step 5: RECO"
    
    RECO_OUTPUT="${WORKDIR}/output_RECO.root"
    
    setup_cmssw12
    
    local cfg_file=$(mktemp --suffix=_reco_cfg.py)
    
    msg_info "Generating RECO config..."
    run_logged "cmsDriver_step3_reco" cmsDriver.py step3 \
        --mc --no_exec \
        --python_filename "${cfg_file}" \
        --eventcontent AODSIM \
        --step RAW2DIGI,L1Reco,RECO,RECOSIM \
        --procModifiers siPixelQualityRawToDigi \
        --datatier AODSIM \
        --conditions 124X_mcRun3_2022_realistic_v12 \
        --beamspot Realistic25ns13p6TeVEarly2022Collision \
        --era Run3 \
        --geometry DB:Extended \
        -n "${MAX_EVENTS}" \
        --customise Configuration/DataProcessing/Utils.addMonitoring \
        --nThreads 4 --nStreams 4 \
        --filein "file:${RAW_OUTPUT}" \
        --fileout "file:${RECO_OUTPUT}"
    
    msg_info "Running RECO step..."
    run_logged "cmsRun_step3_reco" cmsRun "${cfg_file}"
    rm -f "${cfg_file}"
    
    if [[ ! -f "${RECO_OUTPUT}" ]]; then
        msg_error "RECO step failed: ${RECO_OUTPUT} not created"
        return 1
    fi
    
    msg_ok "RECO complete: ${RECO_OUTPUT}"
}

# Step 6: MiniAOD
run_miniaod() {
    msg_step "Step 6: MiniAOD"
    
    MINIAOD_OUTPUT="${WORKDIR}/output_MINIAOD.root"
    
    setup_cmssw12
    
    local cfg_file=$(mktemp --suffix=_miniaod_cfg.py)
    
    msg_info "Generating MiniAOD config..."
    run_logged "cmsDriver_step4_miniaod" cmsDriver.py step4 \
        --mc --no_exec \
        --python_filename "${cfg_file}" \
        --eventcontent MINIAODSIM \
        --step PAT \
        --datatier MINIAODSIM \
        --conditions 124X_mcRun3_2022_realistic_v12 \
        --era Run3 \
        --geometry DB:Extended \
        -n "${MAX_EVENTS}" \
        --customise Configuration/DataProcessing/Utils.addMonitoring \
        --nThreads 4 --nStreams 4 \
        --filein "file:${RECO_OUTPUT}" \
        --fileout "file:${MINIAOD_OUTPUT}"
    
    msg_info "Running MiniAOD step..."
    run_logged "cmsRun_step4_miniaod" cmsRun "${cfg_file}"
    rm -f "${cfg_file}"
    
    if [[ ! -f "${MINIAOD_OUTPUT}" ]]; then
        msg_error "MiniAOD step failed: ${MINIAOD_OUTPUT} not created"
        return 1
    fi
    
    msg_ok "MiniAOD complete: ${MINIAOD_OUTPUT}"
}

# Step 7: Ntuple
run_ntuple() {
    msg_step "Step 7: Ntuple (${ANALYSIS_TYPE})"
    
    NTUPLE_OUTPUT="${WORKDIR}/output_ntuple.root"
    MINIAOD_OUTPUT="${MINIAOD_OUTPUT:-${WORKDIR}/output_MINIAOD.root}"
    local analysis_mode=""
    local package_dir=""
    local cfg_path=""

    if [[ ! -f "${MINIAOD_OUTPUT}" ]]; then
        msg_error "Ntuple input missing: ${MINIAOD_OUTPUT}"
        return 1
    fi

    prepare_cmssw15_from_package "${ANALYSIS_TYPE}" || return 1
    setup_cmssw15

    analysis_mode=$(ntuple_analysis_mode "${ANALYSIS_TYPE}") || {
        msg_error "Unknown analysis type: ${ANALYSIS_TYPE}"
        return 1
    }
    package_dir=$(ntuple_package_dir "${ANALYSIS_TYPE}") || {
        msg_error "Unknown analysis type: ${ANALYSIS_TYPE}"
        return 1
    }
    cfg_path=$(ntuple_cfg_path "${package_dir}")

    if [[ ! -f "${cfg_path}" ]]; then
        msg_error "Ntuple config missing: ${cfg_path}"
        msg_error "Rebuild the ${ANALYSIS_TYPE} worker package with TPS_Onia2MuMu/test/ConfFile_cfg.py included."
        return 1
    fi

    msg_info "Running ${ANALYSIS_TYPE} Ntuple analysis via ${cfg_path}..."
    run_cmsrun_cmssw15 "${cfg_path}" \
        inputFiles="file:${MINIAOD_OUTPUT}" \
        outputFile="${NTUPLE_OUTPUT}" \
        runOnMC=True \
        era=Run2022 \
        analysisMode="${analysis_mode}" \
        maxEvents=-1
    
    if [[ ! -f "${NTUPLE_OUTPUT}" ]]; then
        msg_error "Ntuple step failed: ${NTUPLE_OUTPUT} not created"
        return 1
    fi
    
    msg_ok "Ntuple complete: ${NTUPLE_OUTPUT}"
}

# Step 8: Transfer output
transfer_output() {
    msg_step "Step 8: Transfer to T2_CN_Beijing Storage"
    
    local output_subpath="output/${CAMPAIGN_NAME}/${JOB_ID}"
    
    # Create remote directory
    make_remote_dir "${output_subpath}" || return 1
    
    # Copy final outputs via XRootD
    if [[ -f "${MINIAOD_OUTPUT}" ]]; then
        local miniaod_basename=$(basename "${MINIAOD_OUTPUT}")
        stage_out "${MINIAOD_OUTPUT}" "${output_subpath}/${miniaod_basename}" || return 1
    fi
    
    if [[ -f "${NTUPLE_OUTPUT}" ]]; then
        local ntuple_basename=$(basename "${NTUPLE_OUTPUT}")
        stage_out "${NTUPLE_OUTPUT}" "${output_subpath}/${ntuple_basename}" || return 1
    fi
    
    # Cleanup intermediate files
    if [[ "${CLEANUP}" == "true" ]]; then
        msg_info "Cleaning up intermediate files..."
        rm -f "${WORKDIR}"/*.hepmc
        rm -f "${WORKDIR}"/output_GENSIM.root
        rm -f "${WORKDIR}"/output_RAW.root
        rm -f "${WORKDIR}"/output_RECO.root
        msg_ok "Cleanup complete"
    fi
    
    msg_ok "Transfer complete: ${EOS_BASE}/${output_subpath}/"
}

# ==============================================================================
# Main
# ==============================================================================

usage() {
    cat << EOF
Usage: $0 [options]

Required options:
  --inputs INPUTS       Comma-separated list of pool:index pairs
                        Supports prefixes: GEN:, EOS:, MIX:
  --modes MODES         逗号分隔的 shower 模式
  --analysis TYPE       Analysis type: JJP or JUP
  --campaign NAME       Campaign name (e.g., JJP_DPS1)
  --job-id ID           Job identifier

Optional:
  --workdir DIR           Working directory (default: /srv/<campaign>_<job_id>)
  --enable-ntuple BOOL    是否执行 ntuple 步骤 (true|false)
  --cleanup BOOL          是否清理中间文件 (true|false)
  --skip-to STEP          Skip to specified step (shower|mix|gensim|raw|reco|miniaod|ntuple)
  --stop-at STEP          Stop after specified step
  --max-events N          Limit events for fast local test (default: -1 = all)
  -h, --help              Show this help

Input format examples:
  pool_jpsi_CSCO_g:0          Legacy format (pool:index)
  EOS:pool_jpsi_CSCO_g:0:0    Existing LHE from EOS storage
  GEN:pool_jpsi_CSCO_g:0:1234 LHE generated by DAG，可携带实际 seed
  MIX:pool_2jpsi:0:0          workbook_v2 复合池，按子过程截面选取实际 LHE

Examples:
  # JJP DPS: Two J/psi sources mixed
  $0 --inputs pool_jpsi_CSCO_g:0,pool_jpsi_CSCO_g:1 --modes normal,phi_mpi_off \\
     --analysis JJP --campaign JJP_DPS1 --job-id 0
EOF
    exit 1
}

# Parse arguments
INPUTS=""
MODES=""
ANALYSIS_TYPE=""
CAMPAIGN_NAME=""
JOB_ID=""
WORKDIR=""
CLEANUP="true"
ENABLE_NTUPLE="true"
SKIP_TO=""
STOP_AT=""
MAX_EVENTS=-1

while [[ $# -gt 0 ]]; do
    case $1 in
        --inputs)
            INPUTS="$2"
            shift 2
            ;;
        --modes)
            MODES="$2"
            shift 2
            ;;
        --analysis)
            ANALYSIS_TYPE="$2"
            shift 2
            ;;
        --campaign)
            CAMPAIGN_NAME="$2"
            shift 2
            ;;
        --job-id)
            JOB_ID="$2"
            shift 2
            ;;
        --workdir)
            WORKDIR="$2"
            shift 2
            ;;
        --enable-ntuple)
            ENABLE_NTUPLE="$2"
            shift 2
            ;;
        --cleanup)
            CLEANUP="$2"
            shift 2
            ;;
        --no-cleanup)
            CLEANUP="false"
            shift
            ;;
        --skip-to)
            SKIP_TO="$2"
            shift 2
            ;;
        --stop-at)
            STOP_AT="$2"
            shift 2
            ;;
        --max-events)
            MAX_EVENTS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            msg_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate required arguments
if [[ -z "$INPUTS" ]] || [[ -z "$MODES" ]] || [[ -z "$ANALYSIS_TYPE" ]] || [[ -z "$CAMPAIGN_NAME" ]] || [[ -z "$JOB_ID" ]]; then
    msg_error "Missing required arguments"
    usage
fi

if [[ "${ENABLE_NTUPLE}" != "true" ]] && [[ "${ENABLE_NTUPLE}" != "false" ]]; then
    msg_error "--enable-ntuple must be true or false"
    exit 1
fi

if [[ "${CLEANUP}" != "true" ]] && [[ "${CLEANUP}" != "false" ]]; then
    msg_error "--cleanup must be true or false"
    exit 1
fi

if ! [[ "${MAX_EVENTS}" =~ ^-?[0-9]+$ ]]; then
    msg_error "--max-events must be an integer"
    exit 1
fi

# Default workdir inside the worker scratch to avoid writing to AFS
if [[ -z "${WORKDIR}" ]]; then
    WORKDIR="/srv/${CAMPAIGN_NAME}_${JOB_ID}"
fi
export HOME="${WORKDIR}"

# Parse inputs and modes
IFS=',' read -ra INPUT_SPECS <<< "$INPUTS"
IFS=',' read -ra SHOWER_MODES <<< "$MODES"

# Validate VOMS proxy early (needed for EOS/XRootD listing)
ensure_voms_proxy

# Resolve LHE files from input specs
# Supports: file:/path/to.lhe, GEN:pool:idx, EOS:pool:idx:usage, MIX:pool:idx:usage, pool:idx
LHE_FILES=()
declare -a parts  # Declare array outside loop (no 'local' in main script)
for spec in "${INPUT_SPECS[@]}"; do
    if [[ "$spec" == file:* ]]; then
        # Local file path (from test_full_chain or local runs)
        lhe_file="${spec#file:}"
    elif [[ "$spec" == GEN:* ]]; then
        # Format: GEN:pool_name:lhe_job_idx[:seed]
        IFS=':' read -ra parts <<< "$spec"
        pool_name="${parts[1]}"
        lhe_job_idx="${parts[2]}"
        if [[ ${#parts[@]} -ge 4 ]]; then
            seed="${parts[3]}"
        else
            seed=$((100 + lhe_job_idx))
        fi
        lhe_file="${EOS_LHE_POOL}/${pool_name}/sample_${pool_name}_${seed}.lhe"
        if ! check_remote_file "$lhe_file"; then
            if ! lhe_file=$(get_lhe_file "$pool_name" "$lhe_job_idx"); then
                msg_error "Could not resolve LHE file for: $spec (pool: ${pool_name}, idx: ${lhe_job_idx})"
                exit 1
            fi
        fi
    elif [[ "$spec" == EOS:* ]]; then
        # Format: EOS:pool_name:job_id:usage_idx - existing LHE from EOS
        IFS=':' read -ra parts <<< "$spec"
        pool_name="${parts[1]}"
        job_id="${parts[2]}"
        if ! lhe_file=$(get_lhe_file "$pool_name" "$job_id"); then
            msg_error "Could not resolve LHE file for: $spec (pool: ${pool_name}, job: ${job_id})"
            exit 1
        fi
    elif [[ "$spec" == MIX:* ]]; then
        # Format: MIX:pool_name:job_id:usage_idx - composite pool resolved on worker
        IFS=':' read -ra parts <<< "$spec"
        pool_name="${parts[1]}"
        job_id="${parts[2]}"
        usage_idx="${parts[3]:-0}"
        if ! lhe_file=$(resolve_composite_lhe_file "$pool_name" "$job_id" "$usage_idx"); then
            msg_error "Could not resolve composite LHE file for: $spec (pool: ${pool_name}, job: ${job_id}, usage: ${usage_idx})"
            exit 1
        fi
    else
        # Legacy format: pool_name:index
        pool_name="${spec%:*}"
        index="${spec#*:}"
        if ! lhe_file=$(get_lhe_file "$pool_name" "$index"); then
            msg_error "Could not resolve LHE file for: $spec (pool: ${pool_name}, idx: ${index})"
            exit 1
        fi
    fi
    
    if [[ -z "$lhe_file" ]] || ! check_remote_file "$lhe_file"; then
        msg_error "Could not resolve LHE file for: $spec (tried: ${lhe_file:-<none>})"
        exit 1
    fi
    LHE_FILES+=("$lhe_file")
done

# Print configuration
echo ""
echo "=============================================="
echo "MC Production Chain"
echo "=============================================="
echo "Campaign:     ${CAMPAIGN_NAME}"
echo "Job ID:       ${JOB_ID}"
echo "Analysis:     ${ANALYSIS_TYPE}"
echo "Work dir:     ${WORKDIR}"
echo "Do ntuple:    ${ENABLE_NTUPLE}"
echo "N sources:    ${#LHE_FILES[@]}"
for ((i=0; i<${#LHE_FILES[@]}; i++)); do
    mode_str="${SHOWER_MODES[$i]:-N/A}"
    echo "  Source $((i+1)): ${LHE_FILES[$i]} (mode: ${mode_str})"
done
echo "Max events:   ${MAX_EVENTS}"
echo "=============================================="
echo ""

# Create work directory
mkdir -p "${WORKDIR}"
cd "${WORKDIR}"

# Define step order
STEPS=("shower" "mix" "gensim" "raw" "reco" "miniaod")
if [[ "${ENABLE_NTUPLE}" == "true" ]]; then
    STEPS+=("ntuple")
fi
STEPS+=("transfer")

# Determine starting step
start_idx=0
if [[ -n "$SKIP_TO" ]]; then
    found_skip=0
    for ((i=0; i<${#STEPS[@]}; i++)); do
        if [[ "${STEPS[$i]}" == "$SKIP_TO" ]]; then
            start_idx=$i
            found_skip=1
            break
        fi
    done
    if [[ ${found_skip} -eq 0 ]]; then
        msg_error "Unknown --skip-to step: ${SKIP_TO}"
        exit 1
    fi
fi

# Determine ending step
end_idx=$((${#STEPS[@]} - 1))
if [[ -n "$STOP_AT" ]]; then
    found_stop=0
    for ((i=0; i<${#STEPS[@]}; i++)); do
        if [[ "${STEPS[$i]}" == "$STOP_AT" ]]; then
            end_idx=$i
            found_stop=1
            break
        fi
    done
    if [[ ${found_stop} -eq 0 ]]; then
        msg_error "Unknown --stop-at step: ${STOP_AT}"
        exit 1
    fi
fi

# Summarize planned steps (helps debugging skip/stop logic)
SELECTED_STEPS=()
for ((i=start_idx; i<=end_idx; i++)); do
    SELECTED_STEPS+=("${STEPS[$i]}")
done
msg_info "Planned steps: ${SELECTED_STEPS[*]}"

# Run steps using the selected list (avoids index/loop drift)
for step in "${SELECTED_STEPS[@]}"; do
    case "$step" in
        shower)
            run_shower "${LHE_FILES[@]}"
            ;;
        mix)
            run_mix
            ;;
        gensim)
            run_gensim
            ;;
        raw)
            run_raw
            ;;
        reco)
            run_reco
            ;;
        miniaod)
            run_miniaod
            ;;
        ntuple)
            run_ntuple
            ;;
        transfer)
            transfer_output
            ;;
    esac
done

# If mix was requested but output not found, fail early so tests surface the issue.
# Skip this check when cleanup removed intermediates (CLEANUP=true) or after transfer.
if [[ " ${SELECTED_STEPS[*]} " == *" mix "* ]] && [[ " ${SELECTED_STEPS[*]} " != *" transfer "* ]] && [[ "${CLEANUP}" != "true" ]]; then
    if [[ ! -f "${MIXED_HEPMC:-}" ]]; then
        msg_error "Expected mixed HepMC at ${MIXED_HEPMC:-<unset>} but not found"
        exit 1
    fi
fi

msg_step "Production Complete!"
echo "Campaign:  ${CAMPAIGN_NAME}"
echo "Job ID:    ${JOB_ID}"
echo "Output:    ${EOS_OUTPUT}/${CAMPAIGN_NAME}/${JOB_ID}/"
echo ""
